### ISSUE TITLE
Bluetooth Recognition and glitches

### ISSUE THREAD

**Issue by davidohne** [Lorys89/ASROCK_Z490M-ITX-AC#12]
Hey!
First things first: Thank you for your incredible work! I nearly got the same setup than you do and installing and working with the machine thanks to your work is a dream.

I tried to copy your setup so the only thing I had to buy was a DW1820A and I got one but it looks like if I got another build?!

I'm running Ventura 13.0.1 and most of the things are working. Airdrop is working as well - but it's quite slow. But the main problem is that there seems to be some interference with my airpods. 

After studying everything it looks like my DW1820A is detected different to yours. My peripherals look like this - There is another Vendor and Device ID and perhaps that's also the reason why the card is detected as a dongle in the system report. Is your card detected as internal?

<img width="1224" alt="Screenshot 2022-11-27 at 02 27 08" src="https://user-images.githubusercontent.com/723166/204115188-fe160589-b7ea-4087-8c96-19668b324ff5.png">

System report:

<img width="601" alt="Screenshot 2022-11-27 at 02 29 12" src="https://user-images.githubusercontent.com/723166/204115207-87403a10-1e0a-4ed8-9909-45e0b252cacb.png">

Perhaps it's a problem of the BT firmware of my DW1820A card? I already updated the BrcmPatchRAM to the to 2.6.4 but it didn't help :(

Anyway thank you again for your great work!

**Comment by Lorys89** [comment]
It gives it to you correctly.

**Comment by davidohne** [comment]
Okay, so it's also recognized as THIRD_PARTY_DONGLE at your side?
