### ISSUE TITLE
USB 2.0 devices not recognized on USB 3.0 ports

### ISSUE THREAD

**Issue by atomizasser** [Lorys89/ASROCK_Z490M-ITX-AC#4]
I upgrade to macos 11.3.1 and now if i plug a usb2.0 drive on rear usb panel it is not recognized, but it is recognized if i plug in in front usb. It is normal or a bug?
I use hour efi folder with the 2 usb kext and xhciportlimit quirk enabled.
Thanks.

**Comment by Lorys89** [comment]
from big sur 11.3 the portlimit patch no longer works, so the 21 usb ports can no longer be used all, I did that mapping reducing the ports to 15 and consequently some I had to disable them. if you do not like create your personal mapping following the dortania guide, in my repo I know 2 photos where I specific the hs and ss doors to which physical vegetable gardens corresponds, good work.
