### ISSUE TITLE
The same motherboard model, the same wireless network card, using your EFI boot will cause unlimited restarts

### ISSUE THREAD

**Issue by ljzxzxl** [Lorys89/ASROCK_Z490M-ITX-AC#7]
Detail Device Info：
1. Asrock Z490m itx/ac, BIOS 1.30, DW1820A(CN-0VW3T3)
2. Mac OS 12.0.1 Monterey
3. Graphics card model is AMD R9 Nano (No driver required)

Step：
Use this EFI directly after generating three codes(serial number) 

Detailed situation：
https://xeylon.com/logs/log.mp4

Thank you for viewing, hope to give ideas to solve the problem！

**Comment by Lorys89** [comment]
use my bios prifile

**Comment by ljzxzxl** [comment]
Restore from your BIOS profile in BIOS Setting and try again，Still the same problem（restart and restart）
