### ISSUE TITLE
Same motherboard model and same wireless network card, using this EFI boot will cause unlimited restarts

### ISSUE THREAD

**Issue by ljzxzxl** [Lorys89/ASROCK_Z490M-ITX-AC#9]
Device Info：
Asrock Z490m itx/ac, BIOS 1.30, DW1820A(CN-0VW3T3)
Mac OS 12.0.1 Monterey
Graphics card model is AMD R9 Nano (No driver required)

Problem：
https://xeylon.com/logs/log.mp4

Thank you for viewing, hope to give ideas to solve the problem！

I tried：
Restore from your BIOS profile(https://github.com/Lorys89/ASROCK_Z490M-ITX-AC/raw/main/Screenshot/EXTRA/BIOS%20hack%20profile.BIN) in BIOS Setting and try again，Still the same problem（restart and restart）

**Comment by Lorys89** [comment]
which model ssd or nvme mounts? and the first time you install on this hardware?

**Comment by ljzxzxl** [comment]
There are two hard drives, one from Colorful CN600 256GB and Samsung 970 evo plus 500GB. I have installed macOS on other motherboards before.

**Comment by Lorys89** [comment]
> There are two hard drives, one from Colorful CN600 256GB and Samsung 970 evo plus 500GB. I have installed macOS on other motherboards before.

do you use samsung for macos?

**Comment by ljzxzxl** [comment]
No,  I am using the Colorful CN600 256GB with you EFI

**Comment by Lorys89** [comment]
install macos to samsung 970 evo plus

**Comment by ljzxzxl** [comment]
Sorry, the main problem is that you cannot enter the installation interface through this EFI

**Comment by Lorys89** [comment]
> Sorry, the main problem is that you cannot enter the installation interface through this EFI

never happened any of this, try old version of efi release, to understand if the problem is in the latest release.

**Comment by Lorys89** [comment]
try this efi
[EFI.zip](https://github.com/Lorys89/ASROCK_Z490M-ITX-AC/files/7560745/EFI.zip)
or this efi 
[EFI.zip](https://github.com/Lorys89/ASROCK_Z490M-ITX-AC/files/7560756/EFI.zip)
 or this efi
[EFI.zip](https://github.com/Lorys89/ASROCK_Z490M-ITX-AC/files/7560773/EFI.zip)

**Comment by ljzxzxl** [comment]
Thank you for your kind help. The above EFI files have been tried, but the problem is still not solved. It still restarts during the EFI boot process. Maybe there is a hardware problem. Still thanks.
Close this issue.
